apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels: {
    component: web
  }
spec:
  type: NodePort
  selector:
    component: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
