apiVersion: v1
kind: Service
metadata:
  name: cvh-ca-service
  labels: {
    component: cvh,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: cvh
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
