apiVersion: v1
kind: Service
metadata:
  name: doctor-ca-service
  labels: {
    component: doctor,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: doctor
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
